# Generated by Django 3.2.6 on 2022-09-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220919_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='item',
            new_name='order',
        ),
    ]
